### ISSUE TITLE
Allow for model aliases

### ISSUE THREAD

**Issue by meain** [meain/esa#13]
This is to be defined in a config file. Good time to introduce a config file (config.toml). Wondering if we should consider moving agents into an `agents/` directory.

Something like:

```toml
[model_aliases]

mini = "openai/gpt-4o-mini"
deepseek = "openrouter/deepseek/deepseek-chat-v3-0324:free"
```

The current `--config` flag has to change to `--agent`.
