### ISSUE TITLE
Allow setting directory in which a command in config will be run

### ISSUE THREAD

**Issue by meain** [meain/esa#15]
This would enable something like below

```toml
[[functions]]
name = "run_command"
description = "Run a command in the provided directory"
command = "{{command}}"
pwd = "{{directory}}"
safe = false
```
