### ISSUE TITLE
Multiple little agents

### ISSUE THREAD

**Issue by meain** [meain/esa#6]
Esa might be better as a multiple agents or bots instead of a single all purpose bots. The system prompt, preferred model, and functions can be in a single file(same as the current config.toml file).

**Comment by meain** [comment]
Not much has to change within esa, but this is more of how propose esa to be used. We could additional allow users to specify agent to be used with a `+` syntax. For example:

```
esa +coder <instruction>
```

Will use the config at `~/.config/esa/coder.toml`.

**Comment by meain** [comment]
I guess once we have a couple of agents, we can even have meta agents whose functions will managing other esa agents.

For example, a function for a meta agent could be:

```toml
[[functions]]
name = "ask_coder_agent"
command = "esa +coder '{{instruction}}'

[[functions.parameter]]
name = "instruction"
description = "Instructions or question to the coder agent"
```
